server:
  port: 80
zuul:
  routes:
    info:
      path: /info-management/**
      serviceId: info-service

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka
